import { useState } from "react";
import "@/App.css";
import { ChevronDown, ChevronLeft, ChevronRight, CircleUserRound, Code2, Menu, Play, Search, X, Zap } from "lucide-react";

const curriculum = [
  { level: "01", title: "Pengantar", tag: "Beginner", lessons: ["Pengenalan ESP32 & Pinout", "Setup ESP-IDF Environment", "Hello World & GPIO Blink"] },
  { level: "02", title: "ESP-IDF Scheduler", tag: "Intermediate", lessons: ["Task Creation & Priority", "Queue & Inter-Task Communication", "Software Timers & Event Groups"] },
  { level: "03", title: "RTOS & Multithread", tag: "Advanced", lessons: ["Mutex, Semaphores & Race Conditions", "Dual-Core Pinning", "Memory Management"] },
];

function Sidebar({ mobile, sidebarOpen, openSection, setOpenSection, activeLesson, selectLesson, closeMobile }) {
  const id = mobile ? "mobile-" : "";
  return <aside className={`sidebar ${mobile ? "sidebar-mobile" : ""} ${!sidebarOpen && !mobile ? "sidebar-collapsed" : ""}`} data-testid={`${id}curriculum-sidebar`}>
    <div className="sidebar-brand"><div className="brand-mark" data-testid={`${id}brand-mark`}><Zap size={18} fill="currentColor" /></div>{(sidebarOpen || mobile) && <div><strong>Embedded</strong><span>for Kids</span></div>}{mobile && <button className="icon-button close-mobile" aria-label="Tutup menu" data-testid="close-mobile-menu" onClick={closeMobile}><X size={20} /></button>}</div>
    {(sidebarOpen || mobile) && <><div className="sidebar-caption" data-testid={`${id}curriculum-label`}>KURIKULUM</div><nav className="curriculum-nav" data-testid={`${id}curriculum-navigation`}>{curriculum.map((section, index) => <div className="curriculum-section" key={section.title} data-testid={`${id}curriculum-section-${index}`}><button className={`section-trigger ${openSection === index ? "is-open" : ""}`} onClick={() => setOpenSection(openSection === index ? -1 : index)} data-testid={`${id}curriculum-toggle-${index}`} aria-expanded={openSection === index}><span className="section-number">{section.level}</span><span className="section-copy"><b>{section.title}</b><small>{section.tag}</small></span><ChevronDown size={16} className="chevron" /></button>{openSection === index && <div className="lesson-list" data-testid={`${id}lesson-list-${index}`}>{section.lessons.map((lesson, lessonIndex) => <button key={lesson} className={`lesson-link ${activeLesson === lesson ? "active" : ""}`} onClick={() => selectLesson(lesson)} data-testid={`${id}lesson-${index}-${lessonIndex}`}><span className="lesson-dot" />{lesson}</button>)}</div>}</div>)}</nav><div className="sidebar-footer" data-testid={`${id}sidebar-progress`}><div className="progress-heading"><span>PROGRES BELAJAR</span><b>1 / 9</b></div><div className="progress-track"><span /></div><p>Mulai dari dasar, bangun sesuatu yang nyata.</p></div></>}
  </aside>;
}

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [openSection, setOpenSection] = useState(0);
  const [activeLesson, setActiveLesson] = useState("Pengenalan ESP32 & Pinout");
  const selectLesson = (lesson) => { setActiveLesson(lesson); setMobileOpen(false); };
  return <div className="app-shell" data-testid="app-shell"><Sidebar sidebarOpen={sidebarOpen} openSection={openSection} setOpenSection={setOpenSection} activeLesson={activeLesson} selectLesson={selectLesson} />{mobileOpen && <div className="mobile-overlay" data-testid="mobile-overlay"><Sidebar mobile sidebarOpen={sidebarOpen} openSection={openSection} setOpenSection={setOpenSection} activeLesson={activeLesson} selectLesson={selectLesson} closeMobile={() => setMobileOpen(false)} /></div>}<main className="main-area"><header className="topbar" data-testid="app-header"><div className="header-left"><button className="icon-button desktop-toggle" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Buka atau tutup sidebar" data-testid="sidebar-toggle">{sidebarOpen ? <ChevronLeft size={19} /> : <ChevronRight size={19} />}</button><button className="icon-button mobile-toggle" onClick={() => setMobileOpen(true)} aria-label="Buka menu" data-testid="mobile-menu-button"><Menu size={21} /></button><div className="breadcrumb" data-testid="breadcrumb"><span>Beginner</span><ChevronRight size={14} /><b>{activeLesson}</b></div></div><div className="header-actions"><button className="search-button" data-testid="search-button"><Search size={17} /><span>Cari pelajaran</span><kbd>⌘ K</kbd></button><button className="profile-button" aria-label="Profil pengguna" data-testid="profile-button"><CircleUserRound size={26} /></button></div></header><section className="content-wrap" data-testid="lesson-content"><div className="eyebrow" data-testid="lesson-status"><span className="status-dot" /> PELAJARAN 01 <i>•</i> BEGINNER</div><h1 data-testid="lesson-title">Mulai dari rasa ingin tahu.<br /><em>Bangun dari nol.</em></h1><p className="intro" data-testid="lesson-intro">Selamat datang di Embedded for Kids — ruang belajar untuk memahami cara kerja benda-benda pintar, satu baris kode pada satu waktu.</p><div className="welcome-strip" data-testid="welcome-strip"><div className="strip-icon"><Code2 size={21} /></div><div><b>Siap membuat LED berkedip?</b><span>Ikuti jalur belajar yang sudah kami susun untukmu.</span></div><button className="round-action" data-testid="start-lesson-button" onClick={() => selectLesson("Pengenalan ESP32 & Pinout")}><Play size={16} fill="currentColor" /></button></div><div className="content-divider" /><div className="lesson-preview" data-testid="lesson-preview"><div className="preview-label">PELAJARAN TERPILIH</div><h2>{activeLesson}</h2><p>Kenali papan ESP32, lihat bagian-bagiannya, dan pahami mengapa ia menjadi otak kecil yang seru untuk diprogram.</p><button className="text-action" data-testid="continue-lesson-button">Lanjutkan pelajaran <ChevronRight size={16} /></button></div></section><footer className="page-footer" data-testid="app-footer"><span>© 2024 Embedded for Kids</span><span className="footer-code">ESP32 <i>×</i> ESP-IDF <i>×</i> curiosity</span></footer></main></div>;
}

export default App;