import { useState } from "react";
import "@/App.css";
import "@/curriculum-overrides.css";
import "@/playground-overrides.css";
import "@/onboarding.css";
import { ChevronDown, ChevronLeft, ChevronRight, CircleUserRound, Code2, Compass, FlaskConical, Lightbulb, Menu, Play, Search, Target, Trophy, X, Zap } from "lucide-react";
import { curriculumData, initialLesson } from "@/curriculumData";
import { playgroundData, playgroundSteps, playgroundStepCopy } from "@/playgroundData";

const placementLevels = [
  ["Beginner", "Pengantar C/C++", "Mulai dari fondasi paling dasar", "0"],
  ["Intermediate", "ESP-IDF Scheduler", "Sudah nyaman dengan dasar coding", "2"],
  ["Advanced", "RTOS & Multithread", "Siap menjinakkan sistem yang berjalan bersamaan", "5"],
];

function BookIcon() { return <Lightbulb size={14} />; }

function Onboarding({ onComplete }) {
  const [name, setName] = useState("");
  const [placement, setPlacement] = useState("");
  const [showDonation, setShowDonation] = useState(true);
  const finish = (skip = false) => onComplete({ name: name.trim() || "Penjelajah", placement: skip ? "explorer" : placement });
  return (
    <main className="onboarding-page" data-testid="onboarding-page">
      <div className="onboarding-noise" />
      <div className="onboarding-topline"><div className="onboarding-brand"><span className="brand-mark"><Zap size={18} fill="currentColor" /></span><span><b>Embedded</b><small>for Kids</small></span></div><span className="onboarding-code">ESP32 / ESP-IDF / 001</span></div>
      <section className="onboarding-content"><div className="onboarding-kicker"><span className="status-dot" /> SELAMAT DATANG, PENJELAJAH</div><h1 data-testid="onboarding-title">Belajar dengan<br /><em>rasa ingin tahu.</em></h1><p className="onboarding-intro">Pilih langkah pertama. Sisanya bisa kamu jelajahi sesuka hati — tidak ada jalur yang benar-benar terkunci.</p><label className="name-field" htmlFor="learner-name"><span>SIAPA NAMAMU?</span><input id="learner-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Tulis namamu di sini" data-testid="learner-name-input" /></label><div className="placement-heading"><span>ATUR TITIK MULAI</span><small>Opsional · kamu bebas membuka semua materi</small></div><div className="placement-grid" data-testid="placement-options">{placementLevels.map(([title, subtitle, detail, level]) => <button key={title} className={`placement-card ${placement === title ? "selected" : ""}`} onClick={() => setPlacement(title)} data-testid={`placement-${title.toLowerCase()}`}><span className="placement-level">LEVEL {level}</span><b>{title}</b><strong>{subtitle}</strong><small>{detail}</small>{placement === title && <span className="placement-check">✓</span>}</button>)}</div><div className="onboarding-actions"><button className="primary-start" disabled={!name.trim() || !placement} onClick={() => finish()} data-testid="start-learning-button">Mulai perjalanan <ChevronRight size={17} /></button><button className="skip-button" onClick={() => finish(true)} data-testid="skip-onboarding-button">Lewati &amp; mulai belajar</button></div></section>
      {showDonation && <aside className="donation-card" data-testid="donation-card"><button className="donation-close" onClick={() => setShowDonation(false)} aria-label="Tutup kartu donasi" data-testid="donation-close-button"><X size={15} /></button><div className="donation-icon"><Target size={18} /></div><div><b>Dukung Pembuat Aplikasi</b><span>Opsional · bantu kami terus membuat ruang belajar ini.</span></div><div className="qris-placeholder" data-testid="qris-placeholder"><div className="qr-grid">▦</div><small>QRIS PLACEHOLDER</small></div><button className="donation-skip" onClick={() => finish(true)} data-testid="donation-skip-button">Lewati &amp; mulai belajar <ChevronRight size={14} /></button></aside>}
    </main>
  );
}

function Sidebar({ mobile, sidebarOpen, mode, setMode, openSection, setOpenSection, activeLesson, selectLesson, activeModule, selectModule, closeMobile }) {
  const id = mobile ? "mobile-" : "";
  return <aside className={`sidebar ${mobile ? "sidebar-mobile" : ""} ${!sidebarOpen && !mobile ? "sidebar-collapsed" : ""}`} data-testid={`${id}curriculum-sidebar`}><div className="sidebar-brand"><div className="brand-mark" data-testid={`${id}brand-mark`}><Zap size={18} fill="currentColor" /></div>{(sidebarOpen || mobile) && <div><strong>Embedded</strong><span>for Kids</span></div>}{mobile && <button className="icon-button close-mobile" aria-label="Tutup menu" data-testid="close-mobile-menu" onClick={closeMobile}><X size={20} /></button>}</div>{(sidebarOpen || mobile) && <><div className="mode-switch" data-testid={`${id}mode-switch`}><button className={mode === "curriculum" ? "selected" : ""} onClick={() => setMode("curriculum")} data-testid={`${id}curriculum-mode-tab`}><BookIcon />Kurikulum Akademis</button><button className={mode === "playground" ? "selected" : ""} onClick={() => setMode("playground")} data-testid={`${id}playground-mode-tab`}><FlaskConical size={14} />ESP32 Playground</button></div>{mode === "curriculum" ? <CurriculumNav id={id} openSection={openSection} setOpenSection={setOpenSection} activeLesson={activeLesson} selectLesson={selectLesson} /> : <PlaygroundNav id={id} activeModule={activeModule} selectModule={selectModule} />}</>}</aside>;
}

function CurriculumNav({ id, openSection, setOpenSection, activeLesson, selectLesson }) {
  return <><div className="sidebar-caption" data-testid={`${id}curriculum-label`}>KURIKULUM RESMI</div><nav className="curriculum-nav" data-testid={`${id}curriculum-navigation`}>{curriculumData.map((section, index) => <div className="curriculum-section" key={section.title} data-testid={`${id}curriculum-section-${index}`}><button className={`section-trigger ${openSection === index ? "is-open" : ""}`} onClick={() => setOpenSection(openSection === index ? -1 : index)} data-testid={`${id}curriculum-toggle-${index}`} aria-expanded={openSection === index}><span className="section-number">{section.level === "0" ? <Compass size={14} /> : section.level}</span><span className="section-copy"><b>{section.title}</b><small>{section.tag} · {section.lessons.length} materi</small></span><ChevronDown size={16} className="chevron" /></button>{openSection === index && <div className="lesson-list" data-testid={`${id}lesson-list-${index}`}>{section.lessons.map((lesson) => <button key={lesson.id} className={`lesson-link ${activeLesson.id === lesson.id ? "active" : ""}`} onClick={() => selectLesson(lesson, index)} data-testid={`${id}lesson-${lesson.id}`}><span className="lesson-dot" />{lesson.name}</button>)}</div>}</div>)}</nav><div className="sidebar-footer" data-testid={`${id}sidebar-progress`}><div className="progress-heading"><span>PROGRES BELAJAR</span><b>0 / {curriculumData.reduce((total, item) => total + item.lessons.length, 0)}</b></div><div className="progress-track"><span /></div><p>Mulai dari dasar, bangun sesuatu yang nyata.</p></div></>;
}

function PlaygroundNav({ id, activeModule, selectModule }) { return <nav className="curriculum-nav playground-nav" data-testid={`${id}playground-navigation`}>{playgroundData.map((module, index) => <button key={module.id} className={`playground-module ${activeModule === index ? "active" : ""}`} onClick={() => selectModule(index)} data-testid={`${id}playground-module-${index}`}><span className="module-number">{module.number}</span><span><b>{module.title}</b><small>{module.focus}</small></span><ChevronRight size={14} /></button>)}</nav>; }

function App() {
  const [profile, setProfile] = useState(() => { try { return JSON.parse(window.localStorage.getItem("embedded-for-kids-profile")); } catch { return null; } });
  const [sidebarOpen, setSidebarOpen] = useState(true); const [mobileOpen, setMobileOpen] = useState(false); const [mode, setMode] = useState("curriculum"); const [openSection, setOpenSection] = useState(0); const [activeLesson, setActiveLesson] = useState(initialLesson); const [activeLevel, setActiveLevel] = useState(0); const [activeModule, setActiveModule] = useState(0); const [activePlayStep, setActivePlayStep] = useState("Try");
  const selectLesson = (lesson, levelIndex) => { setActiveLesson(lesson); setActiveLevel(levelIndex); setMobileOpen(false); }; const selectModule = (index) => { setActiveModule(index); setActivePlayStep("Try"); setMobileOpen(false); };
  if (!profile) return <Onboarding onComplete={(nextProfile) => { window.localStorage.setItem("embedded-for-kids-profile", JSON.stringify(nextProfile)); setProfile(nextProfile); }} />;
  const isPlayground = mode === "playground"; const module = playgroundData[activeModule];
  return <div className="app-shell" data-testid="app-shell"><Sidebar sidebarOpen={sidebarOpen} mode={mode} setMode={setMode} openSection={openSection} setOpenSection={setOpenSection} activeLesson={activeLesson} selectLesson={selectLesson} activeModule={activeModule} selectModule={selectModule} />{mobileOpen && <div className="mobile-overlay" data-testid="mobile-overlay"><Sidebar mobile sidebarOpen={sidebarOpen} mode={mode} setMode={setMode} openSection={openSection} setOpenSection={setOpenSection} activeLesson={activeLesson} selectLesson={selectLesson} activeModule={activeModule} selectModule={selectModule} closeMobile={() => setMobileOpen(false)} /></div>}<main className="main-area"><header className="topbar" data-testid="app-header"><div className="header-left"><button className="icon-button desktop-toggle" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Buka atau tutup sidebar" data-testid="sidebar-toggle">{sidebarOpen ? <ChevronLeft size={19} /> : <ChevronRight size={19} />}</button><button className="icon-button mobile-toggle" onClick={() => setMobileOpen(true)} aria-label="Buka menu" data-testid="mobile-menu-button"><Menu size={21} /></button><div className="breadcrumb" data-testid="breadcrumb"><span>{isPlayground ? "Playground" : `Level ${activeLevel}`}</span><ChevronRight size={14} /><b>{isPlayground ? module.title : activeLesson.name}</b></div></div><div className="header-actions"><button className="search-button" data-testid="search-button"><Search size={17} /><span>Cari pelajaran</span><kbd>⌘ K</kbd></button><button className="profile-button" aria-label="Profil pengguna" data-testid="profile-button"><CircleUserRound size={26} /></button></div></header>{isPlayground ? <PlaygroundContent module={module} activeStep={activePlayStep} setActiveStep={setActivePlayStep} /> : <CurriculumContent activeLesson={activeLesson} activeLevel={activeLevel} selectLesson={selectLesson} />}<footer className="page-footer" data-testid="app-footer"><span>© 2024 Embedded for Kids</span><span className="footer-code">ESP32 <i>×</i> ESP-IDF <i>×</i> curiosity</span></footer></main></div>;
}

function CurriculumContent({ activeLesson, activeLevel, selectLesson }) { const hasSelectedLesson = activeLesson.id !== initialLesson.id; return <section className={`content-wrap ${hasSelectedLesson ? "lesson-mode" : ""}`} data-testid="lesson-content">{hasSelectedLesson ? <><div className="eyebrow" data-testid="lesson-status"><span className="status-dot" /> LEVEL {activeLevel} <i>•</i> {curriculumData[activeLevel].tag.toUpperCase()}</div><h1 className="lesson-heading" data-testid="lesson-title">{activeLesson.name}</h1><p className="intro" data-testid="lesson-intro">{activeLesson.description}</p><div className="lesson-context" data-testid="lesson-context"><span className="context-icon"><Code2 size={19} /></span><div><b>{curriculumData[activeLevel].title}</b><span>{curriculumData[activeLevel].description}</span></div></div><div className="content-divider" /><article className="lesson-article" data-testid="lesson-article"><div className="preview-label">RINGKASAN MATERI</div><h2>Yang akan kamu pelajari</h2><p>Materi ini membantumu menghubungkan konsep dasar dengan praktik. Baca perlahan, coba contoh kecilnya, lalu lanjutkan ke materi berikutnya saat kamu siap.</p><button className="text-action" data-testid="continue-lesson-button"><Play size={14} fill="currentColor" /> Mulai belajar</button></article></> : <><div className="eyebrow" data-testid="lesson-status"><span className="status-dot" /> MULAI PERJALANANMU <i>•</i> EMBEDDED FOR KIDS</div><h1 data-testid="lesson-title">Mulai dari rasa ingin tahu.<br /><em>Bangun dari nol.</em></h1><p className="intro" data-testid="lesson-intro">Selamat datang di Embedded for Kids — ruang belajar untuk memahami cara kerja benda-benda pintar, satu baris kode pada satu waktu.</p><div className="welcome-strip" data-testid="welcome-strip"><div className="strip-icon"><Code2 size={21} /></div><div><b>Siap membuat LED berkedip?</b><span>Pilih materi pertama di sidebar untuk mulai belajar.</span></div><button className="round-action" data-testid="start-lesson-button" onClick={() => selectLesson(initialLesson, 0)}><Play size={16} fill="currentColor" /></button></div></>}</section>; }

function PlaygroundContent({ module, activeStep, setActiveStep }) { return <section className="content-wrap playground-content" data-testid="playground-content"><div className="playground-kicker"><span className="sparkle-mark"><FlaskConical size={16} /></span> ESP32 PLAYGROUND <i>•</i> EXPERIMENT {module.number}</div><h1 className="playground-title" data-testid="playground-title">{module.title}<br /><em>buat, rusak, ulangi.</em></h1><p className="intro" data-testid="playground-intro">{module.focus}. Ruang eksperimen ini membantumu belajar dengan cara mencoba langsung, bukan hanya membaca.</p><div className="experiment-card" data-testid="experiment-card"><div className="experiment-topline"><span>DO → SEE → UNDERSTAND</span><b>LAB / {module.number}</b></div><div className="step-tabs" data-testid="playground-step-tabs">{playgroundSteps.map((step) => <button key={step} className={activeStep === step ? "active" : ""} onClick={() => setActiveStep(step)} data-testid={`playground-step-${step.toLowerCase()}`}>{step}</button>)}</div><div className="experiment-body" data-testid="experiment-body"><div className="experiment-visual"><div className={`signal ${activeStep === "Break" ? "broken" : ""}`}><Lightbulb size={42} fill={activeStep === "Try" || activeStep === "Build" ? "currentColor" : "none"} /></div><span>{activeStep === "Break" ? "ERROR / coba lagi" : activeStep === "See" ? "signal terlihat" : "simulasi aktif"}</span></div><div className="experiment-copy"><div className="step-label">{activeStep.toUpperCase()}</div><h2>{activeStep === "Challenge" ? module.challenge : `${activeStep} it: ${module.title}`}</h2><p>{playgroundStepCopy[activeStep]}</p><button className="experiment-action" onClick={() => setActiveStep(activeStep === "Build" ? "Try" : "Build")} data-testid="experiment-action-button">{activeStep === "Build" ? "Ulangi eksperimen" : "Lanjut ke Build"}<ChevronRight size={16} /></button></div></div></div><div className="challenge-strip" data-testid="playground-challenge"><span className="challenge-icon"><Trophy size={18} /></span><div><b>Challenge: {module.challenge}</b><span>Gunakan apa yang baru kamu temukan untuk membuat versimu sendiri.</span></div></div></section>; }

export default App;