export const playgroundSteps = ["Try", "See", "Change", "Break", "Discover", "Challenge", "Build"];

export const tutorialSteps = ["Do", "See", "Break", "Understand"];

const baseModules = [
  ["First Spark", "Nyalakan LED, kedipan, pola", "SOS"],
  ["Make It React", "Tombol & interaksi", "Mini game"],
  ["Make It Feel", "Potentiometer & sensor nilai", "Speed controller"],
  ["Give ESP32 Senses", "Membaca sensor & batas", "Alarm sederhana"],
  ["Make It Talk", "UART / console text", "Console robot"],
  ["Give It a Face", "Display angka/teks/animasi", "Dashboard mini"],
  ["Make Many Things Happen", "Pengenalan multitasking natural", "3 pekerjaan bersamaan"],
  ["Make Them Share", "Concurrency, Queue, Mutex", "Perbaiki race condition"],
  ["Make ESP32 Go Online", "Wi-Fi & kontrol via browser", "Remote control"],
  ["Make ESP32 Talk to ESP32", "Komunikasi antar perangkat", "Mini smart-home"],
  ["Build Something", "Gabungkan kemampuanmu", "Smart Lamp / Weather Station / Robot"],
  ["Create Your Own", "Sandbox terbuka", "Proyek bebas"],
];

const moduleExtras = [
  {
    simKind: "led",
    code: `#include "driver/gpio.h"\n#include "freertos/FreeRTOS.h"\n#include "freertos/task.h"\n\n#define LED_PIN GPIO_NUM_2\n\nvoid app_main(void) {\n    gpio_reset_pin(LED_PIN);\n    gpio_set_direction(LED_PIN, GPIO_MODE_OUTPUT);\n    while (1) {\n        gpio_set_level(LED_PIN, 1);\n        vTaskDelay(pdMS_TO_TICKS(500));\n        gpio_set_level(LED_PIN, 0);\n        vTaskDelay(pdMS_TO_TICKS(500));\n    }\n}`,
    lines: [
      "Meminta driver GPIO ESP-IDF supaya kita bisa mengendalikan pin.",
      "Mengambil kernel FreeRTOS untuk penjadwalan task.",
      "Fungsi task khusus untuk membuat delay ramah RTOS.",
      "",
      "Kita namai pin 2 (LED bawaan board) supaya kode lebih terbaca.",
      "",
      "app_main() adalah pintu masuk program ESP-IDF.",
      "Reset pin agar bebas dari konfigurasi sebelumnya.",
      "Jadikan pin sebagai OUTPUT, artinya kita bisa mengirim listrik keluar.",
      "Loop tak berujung — mikrokontroler suka bekerja terus.",
      "Kirim sinyal HIGH → LED menyala.",
      "Jeda 500 ms tanpa menghentikan sistem lain.",
      "Kirim sinyal LOW → LED mati.",
      "Jeda 500 ms lagi lalu ulang. Inilah kedipan!",
      "",
      "",
    ],
    tutorial: {
      Do: "Tekan Run. Lihat LED biru pada visualisasi berkedip setiap setengah detik. Rasakan momen pertama saat kode kamu benar-benar mengendalikan sesuatu.",
      See: "Perhatikan pola on-off yang sangat teratur. Setiap 500 ms LED berpindah state. Serial monitor tidak menampilkan apa-apa — LED bicara lewat cahaya, bukan teks.",
      Break: "Coba ganti pdMS_TO_TICKS(500) menjadi 5. Apa yang terjadi? LED menyala tampak menyala terus karena mata kita tidak sanggup melihat kedipan super cepat.",
      Understand: "Blink adalah dasar dari semua embedded system: siklus baca–tulis–tunggu. GPIO adalah jembatan antara logika (angka 1 dan 0) dan dunia nyata (arus listrik dan cahaya).",
    },
  },
  {
    simKind: "button",
    code: `#include "driver/gpio.h"\n#include "freertos/FreeRTOS.h"\n#include "freertos/task.h"\n\n#define LED_PIN    GPIO_NUM_2\n#define BUTTON_PIN GPIO_NUM_0\n\nvoid app_main(void) {\n    gpio_set_direction(LED_PIN, GPIO_MODE_OUTPUT);\n    gpio_set_direction(BUTTON_PIN, GPIO_MODE_INPUT);\n    gpio_set_pull_mode(BUTTON_PIN, GPIO_PULLUP_ONLY);\n    while (1) {\n        int pressed = !gpio_get_level(BUTTON_PIN);\n        gpio_set_level(LED_PIN, pressed);\n        vTaskDelay(pdMS_TO_TICKS(20));\n    }\n}`,
    lines: [
      "Driver GPIO ESP-IDF untuk input/output.",
      "Header RTOS untuk delay.",
      "Task helper.",
      "",
      "Pin LED output.",
      "Pin tombol input (BOOT button di banyak board).",
      "",
      "Pintu masuk program.",
      "Set LED sebagai output.",
      "Set tombol sebagai input.",
      "Aktifkan pull-up internal — tombol default HIGH kalau tidak ditekan.",
      "Loop utama.",
      "Baca tombol, invert karena logika aktif LOW.",
      "Nyalakan LED mengikuti tombol.",
      "Delay kecil untuk polling ringan.",
      "",
      "",
    ],
    tutorial: {
      Do: "Tekan tombol pada visualisasi. LED mengikuti — nyala saat ditekan, mati saat dilepas.",
      See: "Respon terasa instan (delay 20 ms). Ini adalah pola input-processing-output pertamamu.",
      Break: "Hilangkan gpio_set_pull_mode. Tombol jadi ‘melayang’ dan nilainya acak. Selamat, kamu baru mengenal ‘floating input’!",
      Understand: "Setiap input digital butuh referensi (pull-up atau pull-down). Tanpa itu, kabel yang tidak terhubung mengambang di antara 0 dan 1.",
    },
  },
  {
    simKind: "pot",
    code: `#include "driver/adc.h"\n#include "esp_log.h"\n\n#define POT_CHANNEL ADC1_CHANNEL_6\nstatic const char *TAG = "POT";\n\nvoid app_main(void) {\n    adc1_config_width(ADC_WIDTH_BIT_12);\n    adc1_config_channel_atten(POT_CHANNEL, ADC_ATTEN_DB_11);\n    while (1) {\n        int raw = adc1_get_raw(POT_CHANNEL);\n        ESP_LOGI(TAG, "raw=%d", raw);\n        vTaskDelay(pdMS_TO_TICKS(200));\n    }\n}`,
    lines: [
      "Driver ADC untuk baca sinyal analog.",
      "Modul logging ESP-IDF.",
      "",
      "Channel ADC1 nomor 6 (pin GPIO34).",
      "Tag untuk memfilter log.",
      "",
      "Pintu masuk.",
      "Set resolusi 12-bit → nilai 0..4095.",
      "Set atenuasi supaya bisa baca tegangan sampai ~3.3V.",
      "Loop utama.",
      "Baca nilai analog mentah.",
      "Kirim ke serial monitor sebagai log INFO.",
      "Jeda 200 ms supaya log tidak membanjiri.",
      "",
      "",
    ],
    tutorial: {
      Do: "Putar potensiometer virtual. Angka pada serial monitor bergerak dari 0 sampai 4095.",
      See: "Nilai ADC linier terhadap posisi knob. Kamu baru saja mengubah ‘analog’ jadi ‘digital’.",
      Break: "Coba baca kanal yang tidak dikonfigurasi. Nilai jadi 0 atau berisik acak — konfigurasi itu penting.",
      Understand: "ADC = Analog to Digital Converter. Ia sampling tegangan dan mengubahnya ke angka. Resolusi menentukan seberapa halus perbedaan yang bisa dibedakan.",
    },
  },
  {
    simKind: "sensor",
    code: `#include "driver/adc.h"\n#include "esp_log.h"\n\n#define LDR_CHANNEL ADC1_CHANNEL_0\nstatic const char *TAG = "SENSE";\n\nvoid app_main(void) {\n    adc1_config_width(ADC_WIDTH_BIT_12);\n    adc1_config_channel_atten(LDR_CHANNEL, ADC_ATTEN_DB_11);\n    while (1) {\n        int light = adc1_get_raw(LDR_CHANNEL);\n        if (light < 800) {\n            ESP_LOGI(TAG, "GELAP (%d)", light);\n        } else {\n            ESP_LOGI(TAG, "TERANG (%d)", light);\n        }\n        vTaskDelay(pdMS_TO_TICKS(400));\n    }\n}`,
    lines: [
      "Driver ADC.",
      "Logging.",
      "",
      "Kanal ADC untuk sensor cahaya (LDR).",
      "Tag log.",
      "",
      "Pintu masuk.",
      "Set resolusi ADC.",
      "Set atenuasi supaya bisa membaca sampai 3.3V.",
      "Loop utama.",
      "Baca nilai LDR.",
      "Cek apakah lebih kecil dari ambang 800.",
      "Jika gelap, catat di log.",
      "Kalau tidak, artinya terang.",
      "Log terang.",
      "",
      "Delay antara pembacaan.",
      "",
      "",
    ],
    tutorial: {
      Do: "Ubah slider cahaya. Serial monitor mencetak GELAP atau TERANG bergantian.",
      See: "Sistem sekarang memberi keputusan sederhana berdasarkan pembacaan sensor.",
      Break: "Tetapkan ambang jadi 5. Sekarang hampir selalu terang. Ambang batas menentukan bias sensor.",
      Understand: "Threshold (ambang) adalah dasar dari alarm, otomatisasi, dan smart home. Sensor tidak berpikir — kamu yang menentukan kapan ia bereaksi.",
    },
  },
  {
    simKind: "serial",
    code: `#include "driver/uart.h"\n#include "esp_log.h"\n#include "string.h"\n\n#define UART_NUM UART_NUM_0\nstatic const char *TAG = "CHAT";\n\nvoid app_main(void) {\n    uart_driver_install(UART_NUM, 1024, 0, 0, NULL, 0);\n    char buf[64];\n    while (1) {\n        int len = uart_read_bytes(UART_NUM, buf, sizeof(buf)-1, pdMS_TO_TICKS(100));\n        if (len > 0) {\n            buf[len] = 0;\n            ESP_LOGI(TAG, "kamu: %s", buf);\n            uart_write_bytes(UART_NUM, "halo balik!\\n", 12);\n        }\n    }\n}`,
    lines: [
      "Driver UART untuk komunikasi serial.",
      "Logging.",
      "String helper.",
      "",
      "UART nomor 0 (yang tersambung ke USB).",
      "Tag log.",
      "",
      "Pintu masuk.",
      "Pasang driver dengan buffer 1024 byte.",
      "Buffer sementara.",
      "Loop utama.",
      "Baca sampai 63 byte selama 100 ms.",
      "Jika ada data,",
      "beri terminator string,",
      "cetak apa yang diketik pengguna,",
      "balas dengan pesan sederhana.",
      "",
      "",
      "",
    ],
    tutorial: {
      Do: "Ketik ‘halo’ di kotak serial. ESP32 (simulasi) menjawab ‘halo balik!’.",
      See: "Komunikasi dua arah pertamamu: ESP32 tidak hanya bicara, tapi juga mendengarkan.",
      Break: "Bikin buffer terlalu kecil (misal 4 byte). Pesan panjang akan terpotong.",
      Understand: "UART adalah protokol paling sederhana — dua kabel (TX, RX) dan waktu. Semua debugging embedded dimulai dari serial monitor.",
    },
  },
  {
    simKind: "led",
    code: `#include "driver/i2c.h"\n#include "ssd1306.h"\n\nvoid app_main(void) {\n    ssd1306_handle_t oled = ssd1306_create(I2C_NUM_0, 0x3C);\n    ssd1306_refresh_gram(oled);\n    ssd1306_clear_screen(oled, 0x00);\n    ssd1306_draw_string(oled, 8, 24, (uint8_t *)"HALO ESP32", 16, 1);\n    ssd1306_refresh_gram(oled);\n    while (1) {\n        vTaskDelay(pdMS_TO_TICKS(1000));\n    }\n}`,
    lines: [
      "Driver I2C.",
      "Library display OLED.",
      "",
      "Pintu masuk.",
      "Buat handle untuk OLED di alamat I2C 0x3C.",
      "Refresh awal.",
      "Bersihkan layar.",
      "Gambar tulisan ‘HALO ESP32’.",
      "Kirim buffer ke layar fisik.",
      "Loop utama diam saja — teks tetap tampil.",
      "Jeda 1 detik.",
      "",
      "",
    ],
    tutorial: {
      Do: "Lihat panel simulasi menampilkan tulisan ‘HALO ESP32’ seperti pada OLED sungguhan.",
      See: "Display membutuhkan setup awal, lalu ‘frame’ dikirim ke layar. Bukan langsung berubah otomatis.",
      Break: "Ubah alamat I2C jadi 0x40. Display diam total — alamat salah = tidak ada yang mendengarkan.",
      Understand: "I2C adalah bus komunikasi dengan alamat. Banyak perangkat bisa berbagi 2 kabel yang sama selama alamatnya berbeda.",
    },
  },
  {
    simKind: "multi",
    code: `#include "freertos/FreeRTOS.h"\n#include "freertos/task.h"\n#include "driver/gpio.h"\n#include "esp_log.h"\n\nstatic void led_task(void *arg) {\n    while (1) {\n        gpio_set_level(GPIO_NUM_2, 1);\n        vTaskDelay(pdMS_TO_TICKS(300));\n        gpio_set_level(GPIO_NUM_2, 0);\n        vTaskDelay(pdMS_TO_TICKS(300));\n    }\n}\nstatic void log_task(void *arg) {\n    while (1) {\n        ESP_LOGI("HEARTBEAT", "alive");\n        vTaskDelay(pdMS_TO_TICKS(1000));\n    }\n}\nvoid app_main(void) {\n    gpio_set_direction(GPIO_NUM_2, GPIO_MODE_OUTPUT);\n    xTaskCreate(led_task, "led", 2048, NULL, 5, NULL);\n    xTaskCreate(log_task, "log", 2048, NULL, 5, NULL);\n}`,
    lines: [
      "Kernel FreeRTOS.",
      "Task API.",
      "GPIO driver.",
      "Logging.",
      "",
      "Task pertama: kedipan LED.",
      "Loop task LED.",
      "Nyalakan LED,",
      "tunggu 300 ms,",
      "matikan LED,",
      "tunggu 300 ms.",
      "",
      "",
      "Task kedua: heartbeat log.",
      "Loop task log.",
      "Cetak ‘alive’ tiap detik.",
      "Delay 1 detik.",
      "",
      "",
      "Pintu masuk.",
      "Set LED sebagai output.",
      "Buat task LED dengan prioritas 5.",
      "Buat task log dengan prioritas 5.",
      "",
    ],
    tutorial: {
      Do: "Jalankan. LED berkedip cepat sementara log mencetak ‘alive’ setiap detik — keduanya sekaligus.",
      See: "Dua task berjalan seolah paralel. Scheduler RTOS membagi CPU untuk mereka.",
      Break: "Ganti vTaskDelay dengan busy loop kosong. Task lain jadi tersendat karena CPU sibuk terus.",
      Understand: "vTaskDelay adalah cara ramah RTOS untuk ‘tidur’. Selama tidur, CPU dipinjamkan ke task lain.",
    },
  },
  {
    simKind: "serial",
    code: `#include "freertos/FreeRTOS.h"\n#include "freertos/queue.h"\n#include "esp_log.h"\n\nstatic QueueHandle_t q;\n\nstatic void producer(void *arg) {\n    int n = 0;\n    while (1) {\n        n++;\n        xQueueSend(q, &n, portMAX_DELAY);\n        vTaskDelay(pdMS_TO_TICKS(500));\n    }\n}\nstatic void consumer(void *arg) {\n    int v;\n    while (1) {\n        if (xQueueReceive(q, &v, portMAX_DELAY)) {\n            ESP_LOGI("QUEUE", "diterima: %d", v);\n        }\n    }\n}\nvoid app_main(void) {\n    q = xQueueCreate(5, sizeof(int));\n    xTaskCreate(producer, "prod", 2048, NULL, 5, NULL);\n    xTaskCreate(consumer, "cons", 2048, NULL, 5, NULL);\n}`,
    lines: [
      "Kernel.",
      "Queue API.",
      "Logging.",
      "",
      "Handle antrian.",
      "",
      "Producer task.",
      "Counter.",
      "Loop.",
      "Naikkan counter.",
      "Kirim ke antrian.",
      "Jeda 500 ms.",
      "",
      "",
      "Consumer task.",
      "Tempat penampung.",
      "Loop.",
      "Ambil dari antrian (menunggu jika kosong).",
      "Log nilai yang diterima.",
      "",
      "",
      "",
      "Pintu masuk.",
      "Buat antrian kapasitas 5.",
      "Buat producer.",
      "Buat consumer.",
      "",
    ],
    tutorial: {
      Do: "Jalankan. Serial monitor menampilkan angka bertambah tiap 500 ms.",
      See: "Producer menaruh data, consumer mengambil — mereka tidak saling menyentuh langsung.",
      Break: "Naikkan prioritas producer jauh di atas consumer. Antrian bisa penuh dan producer stuck.",
      Understand: "Queue adalah cara aman berbagi data antar-task. Tidak ada race condition selama semua akses lewat queue.",
    },
  },
  {
    simKind: "wifi",
    code: `#include "esp_wifi.h"\n#include "esp_event.h"\n#include "esp_netif.h"\n#include "nvs_flash.h"\n\nvoid app_main(void) {\n    nvs_flash_init();\n    esp_netif_init();\n    esp_event_loop_create_default();\n    esp_netif_create_default_wifi_sta();\n    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();\n    esp_wifi_init(&cfg);\n    wifi_config_t wc = {\n        .sta = { .ssid = "SSID", .password = "PASSWORD" }\n    };\n    esp_wifi_set_mode(WIFI_MODE_STA);\n    esp_wifi_set_config(WIFI_IF_STA, &wc);\n    esp_wifi_start();\n    esp_wifi_connect();\n}`,
    lines: [
      "Header Wi-Fi.",
      "Event loop system.",
      "Networking interface.",
      "Non-volatile storage (dipakai Wi-Fi untuk simpan kredensial).",
      "",
      "Pintu masuk.",
      "Init NVS.",
      "Init lapisan networking.",
      "Buat event loop default.",
      "Buat interface Wi-Fi station.",
      "Ambil konfigurasi default.",
      "Init Wi-Fi.",
      "Set kredensial jaringan.",
      "",
      "",
      "Set mode station (client).",
      "Terapkan config.",
      "Nyalakan Wi-Fi.",
      "Coba tersambung.",
      "",
    ],
    tutorial: {
      Do: "Klik Connect di panel simulasi. Setelah 2 detik status berubah menjadi ‘Connected’.",
      See: "Wi-Fi butuh banyak lapisan (NVS → netif → event loop → wifi_init). Ini alur khas ESP-IDF.",
      Break: "Kosongkan SSID. Perangkat tidak akan pernah terhubung karena tidak tahu jaringan mana.",
      Understand: "Wi-Fi bukan magic. Ia rangkaian modul yang saling bergantung dan diatur lewat event.",
    },
  },
  {
    simKind: "wifi",
    code: `#include "esp_now.h"\n#include "esp_wifi.h"\n\nuint8_t peer_mac[] = {0x24,0x0A,0xC4,0x00,0x00,0x01};\n\nstatic void on_recv(const uint8_t *mac, const uint8_t *data, int len) {\n    ESP_LOGI("ESP-NOW", "dari %02x: %.*s", mac[5], len, data);\n}\n\nvoid app_main(void) {\n    esp_now_init();\n    esp_now_register_recv_cb(on_recv);\n    esp_now_peer_info_t p = {0};\n    memcpy(p.peer_addr, peer_mac, 6);\n    esp_now_add_peer(&p);\n    const char *msg = "halo ESP32 lain!";\n    esp_now_send(peer_mac, (uint8_t *)msg, strlen(msg));\n}`,
    lines: [
      "Header ESP-NOW.",
      "Header Wi-Fi (ESP-NOW ride di atas Wi-Fi).",
      "",
      "Alamat MAC perangkat tujuan.",
      "",
      "Callback saat menerima paket.",
      "Log nilai dari byte terakhir MAC + isi.",
      "",
      "",
      "Pintu masuk.",
      "Init ESP-NOW.",
      "Daftarkan callback penerima.",
      "Info peer kosong.",
      "Salin alamat peer.",
      "Tambahkan sebagai peer resmi.",
      "Pesan singkat.",
      "Kirim pesan.",
      "",
      "",
    ],
    tutorial: {
      Do: "Klik Send. Terminal simulasi menampilkan pesan berpindah dari device A ke device B.",
      See: "Komunikasi tanpa Wi-Fi router — dua ESP32 bicara langsung.",
      Break: "Ganti MAC tujuan menjadi acak. Pesan hilang di udara.",
      Understand: "ESP-NOW adalah protokol ringan Espressif. Cocok untuk sensor mesh dan smart home lokal.",
    },
  },
  {
    simKind: "led",
    code: `#include "driver/gpio.h"\n#include "driver/adc.h"\n#include "freertos/FreeRTOS.h"\n#include "freertos/task.h"\n\n#define LED GPIO_NUM_2\n#define LDR ADC1_CHANNEL_0\n\nvoid app_main(void) {\n    gpio_set_direction(LED, GPIO_MODE_OUTPUT);\n    adc1_config_width(ADC_WIDTH_BIT_12);\n    adc1_config_channel_atten(LDR, ADC_ATTEN_DB_11);\n    while (1) {\n        int light = adc1_get_raw(LDR);\n        gpio_set_level(LED, light < 1000 ? 1 : 0);\n        vTaskDelay(pdMS_TO_TICKS(200));\n    }\n}`,
    lines: [
      "GPIO.",
      "ADC.",
      "RTOS.",
      "Task API.",
      "",
      "Alias pin LED.",
      "Alias kanal ADC.",
      "",
      "Pintu masuk.",
      "Set LED output.",
      "Set resolusi ADC.",
      "Set atenuasi.",
      "Loop utama.",
      "Baca sensor.",
      "Nyalakan LED kalau gelap.",
      "Delay ringan.",
      "",
      "",
    ],
    tutorial: {
      Do: "Turunkan cahaya di simulasi. LED otomatis menyala. Kamu baru saja membuat ‘Smart Lamp’.",
      See: "Sistem sekarang menggabungkan input analog + output digital — kombinasi pertama menuju produk.",
      Break: "Naikkan ambang jadi 4000. LED nyala terus meskipun terang.",
      Understand: "Sebuah proyek nyata biasanya kombinasi 2-3 modul kecil. Kamu sudah punya semua bahannya.",
    },
  },
  {
    simKind: "sandbox",
    code: `// Sandbox: pilih blok kamu sendiri.\n// contoh: LED + tombol + logika bebas\n#include "driver/gpio.h"\n\nvoid app_main(void) {\n    gpio_set_direction(GPIO_NUM_2, GPIO_MODE_OUTPUT);\n    gpio_set_direction(GPIO_NUM_0, GPIO_MODE_INPUT);\n    gpio_set_pull_mode(GPIO_NUM_0, GPIO_PULLUP_ONLY);\n    while (1) {\n        int b = !gpio_get_level(GPIO_NUM_0);\n        gpio_set_level(GPIO_NUM_2, b);\n    }\n}`,
    lines: [
      "Komentar pengingat.",
      "",
      "Include minimal.",
      "",
      "Pintu masuk.",
      "Set LED sebagai output.",
      "Set tombol sebagai input.",
      "Aktifkan pull-up.",
      "Loop kosong siap kamu isi.",
      "Baca tombol.",
      "Terapkan ke LED.",
      "",
      "",
    ],
    tutorial: {
      Do: "Mulai dari template sederhana ini. Tambahkan sensor, komunikasi, atau tampilan sesukamu.",
      See: "Sandbox tidak memaksa pola tertentu. Kamu pilih inputnya, kamu pilih outputnya.",
      Break: "Bebas! Salah adalah bagian dari pembelajaran di sini.",
      Understand: "Kreativitas embedded muncul saat kamu berani menggabungkan hal-hal yang belum pernah dicoba orang lain.",
    },
  },
];

export const playgroundData = baseModules.map(([title, focus, challenge], index) => ({
  id: `play-${index}`,
  number: String(index + 1).padStart(2, "0"),
  title,
  focus,
  challenge,
  ...moduleExtras[index],
}));

export const playgroundStepCopy = {
  Try: "Coba eksperimen kecilnya dan lihat apa yang terjadi saat kamu menekan tombol mulai.",
  See: "Amati perubahan pada output ESP32 dan hubungkan hasilnya dengan input yang kamu berikan.",
  Change: "Ubah satu nilai, pola, atau baris logika lalu bandingkan hasilnya dengan percobaan awal.",
  Break: "Sengaja buat sistemnya 'rusak'. Kesalahan adalah petunjuk paling seru untuk belajar.",
  Discover: "Temukan alasan di balik perilaku sistem dan catat pola yang kamu lihat.",
  Challenge: "Tantanganmu: selesaikan misi ini dengan kreativitasmu sendiri.",
  Build: "Gabungkan ide-ide tadi menjadi sesuatu yang bisa kamu tunjukkan dan kembangkan.",
};
